name: my-training-job
workdir: ./workdir
num_nodes: 1

resources:
  accelerators: T4
  cpus: 4+
  memory: 2+

envs:
  RUN_NAME: run-v1
  LEARNING_RATE: 2e-5
  BATCH_SIZE: 16
  EPOCHS: 3

file_mounts:
  /datasets-s3:
    source: s3://skypilot-tutorial-bucket
    mode: COPY
  /results-s3:  # MOUNT mode
    name: skypilot-tutorial-results-bucket
    store: s3

setup: |
  uv venv --seed --python 3.11
  source .venv/bin/activate

  uv pip install -r requirements.txt

run: |
  source .venv/bin/activate

  python train.py \
    --data-dir /datasets-s3 \
    --learning-rate $LEARNING_RATE \
    --batch-size $BATCH_SIZE \
    --epochs $EPOCHS \
    --output-dir /results-s3/$RUN_NAME
